version: '3.9'

services:
  rabbitmq1:
    image: rabbitmq:4.0-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    volumes:
      - ./rabbitmq1_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      rabbitmq_net:
        ipv4_address: 192.168.30.2
    ports:
      - "15672:15672" # RabbitMQ 管理界面
      - "5672:5672"   # AMQP 端口

  rabbitmq2:
    image: rabbitmq:4.0-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq2"
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    volumes:
      - ./rabbitmq2_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      rabbitmq_net:
        ipv4_address: 192.168.30.3
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:4.0-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq3"
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    volumes:
      - ./rabbitmq3_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      rabbitmq_net:
        ipv4_address: 192.168.30.4
    depends_on:
      - rabbitmq1

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:

networks:
  rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24