/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.order;

import org.springframework.amqp.rabbit.annotation.EnableRabbit;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jdbc.repository.config.EnableJdbcRepositories;
import org.springframework.data.relational.core.mapping.DefaultNamingStrategy;
import org.springframework.data.relational.core.mapping.NamingStrategy;

@SpringBootApplication
@EnableJdbcRepositories
@EnableRabbit
public class App {

    @Bean
    public NamingStrategy namingStrategy() {
        return new DefaultNamingStrategy();
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
